name: Continuous Deployment 
on:
  release:
    types: [created]
jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        registry-url: 'https://registry.npmjs.org'
        node-version: '16.x'
    - name: cache node modules
      uses: ./.github/actions/cache-node-modules
    - name: build
      run: npm run build
    - run: npm publish --access public --scope=@noahvarghese
      env: 
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  github-packages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        registry-url: 'https://npm.pkg.github.com'
        node-version: '16.x'
    - name: cache node modules
      uses: ./.github/actions/cache-node-modules
    - name: build
      run: npm run build
    - run: npm publish --access public --scope=@noahvarghese
      env: 
        NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}


