name: Continuous Deployment

on:
  push:
    branches: [main]

jobs:
  continuous-deployment:
    if: "(!contains(github.event.head_commit.message, 'pipeline skip') && !contains(github.event.head_commit.message, 'skip pipeline')) || (!contains(github.event.head_commit.message, 'cd skip') && !contains(github.event.head_commit.message, 'skip cd'))"
    runs-on: ubuntu-latest
    env:
      NPM_ID: ${{ secrets.NPM_PWD }}
      NPM_PWD: ${{ secrets.NPM_PWD }}
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - uses: actions/setup-node@v2
      - name: cache node modules
        uses: ./.github/actions/cache-node-modules
      - name: build
        run: npm run build
