name: Release
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
    - uses: actions/setup-node@v2
    - name: cache node modules
      uses: ./.github/actions/cache-node-modules
    - name: build
      run: npm run build
    - run: npm publish
      env: 
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
